//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laba2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instytyts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Instytyts()
        {
            this.Kafedra = new HashSet<Kafedra>();
        }
    
        public int Instytyts_id { get; set; }
        public string Instytyts_name { get; set; }
        public string Director { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kafedra> Kafedra { get; set; }
    }
}
