//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laba2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teachers_Subject
    {
        public int Teacher_Subject_id { get; set; }
        public int Teachers_FK { get; set; }
        public int Subject_FK { get; set; }
    
        public virtual Subjects Subjects { get; set; }
        public virtual Teachers Teachers { get; set; }
    }
}
