// <auto-generated />
namespace Laba5_1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class new_colm : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(new_colm));
        
        string IMigrationMetadata.Id
        {
            get { return "201710260636545_new_colm"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
